### PR TITLE
Fix texture format SZ_A8 (0x19)

### PR DESCRIPTION
**Pull request by JayFoxRox**
Fixes copyright and start message in DoA3.

### CODE REVIEW

**Comment by espes** [comment]
seems legit

**Comment by PatrickvL** [comment]
I'm curious - does it look like this now? https://youtu.be/PjdOPluLR7Q

**Comment by CodeAsm** [comment]
compile and test it ?

**Comment by PatrickvL** [comment]
With the compile instructions as they are now? No thanks... ;)

**Pull request merged**
