### PR TITLE
imgur album for screenshots and link to youtube

### PR DESCRIPTION
**Pull request by JayFoxRox**
Only an idea, not sure if the code is good or anything. Just messing around.
I should probably rename my "JayFoxRox" imgur account to "xqemu" with a new password if we do this.

Thoughts?

### CODE REVIEW

**Comment by LavenderMoon** [comment]
I'd recommend making a new Imgur account instead. Does Imgur have any sort of developer API for uploading images?

**Comment by JayFoxRox** [comment]
Yes, but I can also change my subdomain [just tested, it's already http://xqemu.imgur.com/ now] and I only recently registered my account to upload xqemu screenshots.
Changing the e-mail is also possible and we can also change the password.
We should probably also register the "xqemu" channel on YouTube asap.
I'm a YouTube partner but I'm not sure if I can simply register a new channel. We couldn't transfer the videos either.

**Comment by LavenderMoon** [comment]
I think you can create a new channel without creating a new account. https://support.google.com/youtube/answer/1646861?hl=en

**Comment by espes** [comment]
Youtube urls are separate from accounts these days. I went and linked the google+ page to google.com/+xqemu and youtube.com/xqemu though

**Comment by LavenderMoon** [comment]
Nice.

**Comment by DerekTurtleRoe** [comment]
We can close this, can't we?

@espes @JayFoxRox

**Comment by DerekTurtleRoe** [comment]
@JayFoxRox Hey, how can I best get a hold of you so I can talk about your XQEMU wiki? I want to make some changes, but I want to discuss it first. I just want to contribute.

@espes Are you guys going to sync your Wikis on GitHub eventually?

**Comment by JayFoxRox** [comment]
xqemu irc channel. Check http://xqemu.com for the current server / channel

**Comment by DerekTurtleRoe** [comment]
@JayFoxRox OK, thanks.

**Comment by JayFoxRox** [comment]
I'll close this - it's ancient and won't be merged anyway :P .

But I think we should have a new website with more media and more information for developers.
The project currently looks very inactive / dead from the outside.

**Comment by DerekTurtleRoe** [comment]
@JayFoxRox 
I might be willing to help with that if you want. 😄

**Comment by JayFoxRox** [comment]
No need to ping me specifically. This is an open-source project, not my personal project.

Any contribution is welcome, but don't waste your time on something which will fail a review (which it will if you don't discuss it prior).
(Maintainers will want the best for the project, so if you have good reasons (and contributions), even controversial changes, can be accepted)

If you think it's an issue: Create a issue on github, discuss it there, if nobody replies within a couple of days / weeks explicitly ask people (any stakeholders: users and devs / maintainers)  (on irc / reddit / .. ) and then, depending on the feedback, implement it and go through the standard PR review process.

---

Personally I think the website is an issue (but #92 is still worse), however, maintaining a website is lots of work and hard to get right. I think it also easily distracts from working on the main project (emulator), so I didn't create an issue yet.
(We have had 3 core-devs with varying activity, which is not enough to maintain Xbox research, toolchains for devs, tools for users, emulation .. and also a website).

**Comment by DerekTurtleRoe** [comment]
The reason I pinged you was because you and espes are the only people I knew who were working on the project. I assumed most of the contributors were leftovers from when you forked QEMU.

Anyway, you may be right, it might be a good idea to focus on the emulator since it is in pretty early stages.

**Comment by JayFoxRox** [comment]
If you want to work on a website: do it (by doing what I said).
However, if you are also willing to work on the emulator: Work on the emulator instead.

**Pull request closed without merging**
